[package]
name = "varlink_stdinterfaces"
version = "5.0.4"
authors = ["Harald Hoyer <harald@redhat.com>"]
edition = "2018"

license = "MIT/Apache-2.0"
documentation = "https://github.com/varlink/rust/blob/master/varlink/README.md"
homepage = "https://github.com/varlink/rust/blob/master/varlink"
repository = "https://github.com/varlink/rust"
description = "varlink common interfaces"
build = "build.rs"

[dependencies]
varlink = { version = "5", path = "../varlink" }
serde = "1"
serde_derive = "1"
serde_json = "1"
failure = "0.1"
failure_derive = "0.1"

[build-dependencies]
varlink_generator = { version = "6", path = "../varlink_generator" }

