[package]
name = "varlink_stdinterfaces"
version = "7.0.0"
authors = ["Harald Hoyer <harald@redhat.com>"]
edition = "2018"

license = "MIT/Apache-2.0"
documentation = "https://github.com/varlink/rust/blob/master/varlink/README.md"
homepage = "https://github.com/varlink/rust/blob/master/varlink_stdinterfaces"
repository = "https://github.com/varlink/rust"
description = "varlink common interfaces"
build = "build.rs"

[dependencies]
varlink = { version = "7", path = "../varlink" }
serde = "1"
serde_derive = "1"
serde_json = "1"
chainerror = { version="0.4.4", optional = true }

[features]
default = []
chain-error = [ "chainerror", "varlink/chain-error" ]

[build-dependencies]
varlink_generator = { version = "7", path = "../varlink_generator" }
