[package]
name = "varlink_derive"
version = "0.1.0"
authors = ["Harald Hoyer <harald@redhat.com>"]
edition = "2018"

[lib]
proc_macro = true
name = "varlink_derive"
path = "src/lib.rs"

[dependencies]
varlink_generator = { version = "7.1", path = "../varlink_generator" }
