os:
- linux
- osx
- windows

language: rust

rust:
- stable
- beta
- nightly

cache:
  timeout: 1000
  cargo: true

before_cache:
- rm -rf target

before_script: |
  cargo install --force cargo-audit

script:
- cargo update
- cargo audit
- cargo build --all
- cargo test --all

matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/8cfd8d5fa3c31aa3d0c3
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

