language: rust
rust:
- stable
addons:
  apt:
    packages:
    - libssl-dev
cache: cargo
script:
- cargo build --verbose --all
- cargo test --verbose --all
after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin && cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi
env:
  global:
    secure: DdzrmEtTAvbmIf1+us7mI+BQkJb9QIJf0aSHEcPjoU88pIaEVc/hB2oS1gBO1zHf6qfA6siEl6j5Zbue31Ybdm3O+kKEl0jfSCaYaxlOBaoMP3Nxz/wFoJYcVyYAUefutCqrv9GJau8zzikD38ghxd1FsNGAK0vZN69PqLk8r7oUsKZ9Eet0TBF55dJseJaFfaufnUoBUAPV2IGTeN2PRLm9j54OfMcCYm8UNqoFQMzsMaTWUifzUceabTP/YbzDw95GVIUrD1a+e6AwFnAy73PDA7M0TvbCz8IdfnwWYZf/6z9lfrewJGYk9Hmt1saocphY9O7SEG/7jYQJD4OSsm2+Fj5tg9AqK3yMVoA17NOgzZA/0glXxQFB69fxIS7tlaZiGwUWJSDm6Jf7UHsAKd/Szr6ZKPCXthxe2GsENA0146Tls9ahoA9Nkw897xwavL8oezIwLjlqKVSJ6qWP5MHnxoXsPaLPd+/utOTOvSqLnmXbAHvcHbz63mRSkU2OuV4gGXi60iZijV3XDz7M1vkabSjR3lmGk/mx33IQ4c9McjzYUixHAhMH2sn9Ki6hs428xAr3UUwFCChlAva08R3B1DKaQ0UJ1tNmhDleVEt2ByyaJye5pJp8iXgRity4pY+qGgJ8RBFJ8ltJJ6gjgOEt/T7x5s+C1CClyJJwpfk=
