language: rust
rust:
  - stable
cache: cargo
script:
  - pushd varlink_parser
  - cargo build --verbose
  - cargo test --verbose
  - cargo run --example validate ../examples/varlink-server-example/src/io.systemd.network.varlink
  - popd
  - pushd varlink
  - cargo build --verbose
  - cargo test --verbose
  - cargo run --bin varlink-rust-generator ../examples/varlink-server-example/src/io.systemd.network.varlink
  - popd
  - pushd examples/varlink-server-example
  - cargo build --verbose
  - cargo test --verbose
  - popd
  - pushd examples/varlink-server-more
  - cargo build --verbose
  - cargo run unix:@test-varlink-server-more-$$
  - cargo run unix:/tmp/varlink-server-more-test-$$
  - cargo run tcp:0.0.0.0:12345
  - cargo test --verbose
  - popd
  - pushd examples/varlink-server-ping
  - cargo build --verbose
  - cargo test --verbose
  - popd
