[workspace]
members = [
    "varlink_parser",
    "varlink",
    "examples/varlink-certification",
    "examples/varlink-server-example",
    "examples/varlink-server-more",
    "examples/varlink-server-complex",
    "examples/varlink-server-ping",
    "examples/varlink-client-ping",
    "examples/varlink-client-more",
]
