[package]
name = "varlink"
version = "0.1.0"
authors = ["Harald Hoyer <harald@redhat.com>"]
build = "build.rs"

[dependencies]
itertools = "0"
serde = "1"
serde_derive = "1"
serde_json = "1"
bytes = "0"

[build-dependencies]
peg = "0.5"

