[package]
name = "varlink"
version = "0.1.0"
authors = ["Harald Hoyer <harald@redhat.com>"]
build = "build.rs"

[dependencies]
itertools = "0.6"
serde = "1.0.8"
serde_derive = "1.0.8"
serde_json = "1.0"
bytes = "0.4"
futures = "0.1"
tokio-io = "0.1"
tokio-core = "0.1"
tokio-proto = "0.1"
tokio-service = "0.1"
macro-attr = "0.2.0"

[build-dependencies]
peg = "0.5"

