[package]
name = "varlink"
version = "0.1.0"
authors = ["Harald Hoyer <harald@redhat.com>"]
build = "build.rs"

[dependencies]

[build-dependencies]
peg = "0.5.1"

[replace]
"peg:0.5.1" = { git = 'https://github.com/haraldh/rust-peg.git' }

[[example]]
name = "validate"
