[package]
name = "varlink"
version = "0.1.0"
authors = ["Harald Hoyer <harald@redhat.com>"]
build = "build.rs"

[dependencies]
itertools = "0.5.9"

[build-dependencies]
peg = "0.5.1"

[[example]]
name = "validate"
