[package]
name = "varlink"
version = "0.1.5"
authors = ["Harald Hoyer <harald@redhat.com>"]
license = "MIT/Apache-2.0"
documentation = "https://github.com/varlink/rust/blob/master/varlink/README.md"
homepage = "https://github.com/varlink/rust/blob/master/varlink"
repository = "https://github.com/varlink/rust"
description = "Client and server support for the varlink protocol."
readme = "README.md"

keywords = ["varlink", "ipc", "rpc", "protocol"]
categories = ["os", "development-tools", "network-programming"]

[lib]
name = "varlink"
path = "src/lib.rs"

[[bin]]
name = "varlink-generator"
path = "src/bin/varlink-generator.rs"

[dependencies]
itertools = "0"
serde = "1"
serde_derive = "1"
serde_json = "1"
bytes = "0"
varlink_parser = { version = "0.1", path = "../varlink_parser" }

[badges]
travis-ci = { repository = "varlink/rust" }

[dev-dependencies]
varlink_parser = { version = "0", path = "../varlink_parser" }
