[package]
name = "more"
version = "2.0.0"
authors = ["Harald Hoyer <harald@redhat.com>"]
build = "build.rs"
edition = "2018"
publish = false

[dependencies]
varlink = { version = "9", path = "../../varlink" }
serde = "1"
serde_derive = "1"
serde_json = "1"
getopts = "0"

[build-dependencies]
varlink_generator = { version = "8", path = "../../varlink_generator" }

[dev-dependencies]
static_assertions = "1.1.0"