[package]
name = "varlink-certification"
version = "0.1.0"
authors = ["Harald Hoyer <harald@redhat.com>"]
build = "build.rs"

[dependencies]
varlink = { path = "../varlink" }
serde = "1"
serde_derive = "1"
serde_json = "1"
getopts = "0"
error-chain = "0.11"

[build-dependencies]
varlink = { path = "../varlink" }
