[package]
name = "varlink-certification"
version = "2.0.2"
authors = ["Harald Hoyer <harald@redhat.com>"]
build = "build.rs"
edition = "2018"
publish = false

[dependencies]
varlink = { version = "9", path = "../varlink" }
serde = "1"
serde_derive = "1"
serde_json = "1"
getopts = "0"
chainerror = "0.4.2"

[build-dependencies]
varlink_generator = { version = "8", path = "../varlink_generator" }

[dev-dependencies]
escargot = "0.5.0"
chainerror = "0.4.2"
