[package]
name = "varlink-certification"
version = "2.0.0"
authors = ["Harald Hoyer <harald@redhat.com>"]
build = "build.rs"

[dependencies]
varlink = { version = "3", path = "../varlink" }
serde = "1"
serde_derive = "1"
serde_json = "1"
getopts = "0"
failure_derive = "0.1.2"
failure = "0.1.2"

[build-dependencies]
varlink = { version = "3", path = "../varlink" }

[dev-dependencies]
assert_cmd = "0.9"
varlink = { version = "3", path = "../varlink" }
