[package]
name = "varlink-cli"
version = "2.1.1"
authors = ["Harald Hoyer <harald@redhat.com>"]
license = "MIT/Apache-2.0"
documentation = "https://github.com/varlink/rust/blob/master/varlink/README.md"
homepage = "https://github.com/varlink/rust/blob/master/varlink"
repository = "https://github.com/varlink/rust"
description = "varlink command line tool"

[[bin]]
name = "varlink"
path = "src/main.rs"

[dependencies]
varlink = { version = "3", path = "../varlink" }
varlink_service = { version = "0.1", path = "../varlink_service" }
varlink_parser = { version = "1", path = "../varlink_parser" }
serde = "1"
serde_json = "1"
clap = "2"
failure_derive = "0.1.2"
failure = "0.1.2"

[build-dependencies]
varlink = { version = "3", path = "../varlink" }

[dev-dependencies]
assert_cmd = "0.9"
varlink_parser = { version = "1", path = "../varlink_parser" }
varlink = { version = "3", path = "../varlink" }
varlink_service = { version = "0.1", path = "../varlink_service" }
