[package]
name = "varlink-cli"
version = "3.1.0"
authors = ["Harald Hoyer <harald@redhat.com>"]
edition = "2018"

license = "MIT/Apache-2.0"
documentation = "https://github.com/varlink/rust/blob/master/varlink/README.md"
homepage = "https://github.com/varlink/rust/blob/master/varlink"
repository = "https://github.com/varlink/rust"
description = "varlink command line tool"

[[bin]]
name = "varlink"
path = "src/main.rs"

[dependencies]
varlink = { version = "5.2", path = "../varlink" }
varlink_stdinterfaces = { version = "5", path = "../varlink_stdinterfaces" }
varlink_parser = { version = "2.2", path = "../varlink_parser" }
serde = "1"
serde_json = "1"
clap = "2"
failure_derive = "0.1"
failure = "0.1"
colored_json = "1"

[dev-dependencies]
escargot = "0.3"
