[package]
name = "varlink-cli"
version = "2.2.0"
authors = ["Harald Hoyer <harald@redhat.com>"]
license = "MIT/Apache-2.0"
documentation = "https://github.com/varlink/rust/blob/master/varlink/README.md"
homepage = "https://github.com/varlink/rust/blob/master/varlink"
repository = "https://github.com/varlink/rust"
description = "varlink command line tool"

[[bin]]
name = "varlink"
path = "src/main.rs"

[dependencies]
varlink = { version = "5.0", path = "../varlink" }
varlink_stdinterfaces = { version = "5.0", path = "../varlink_stdinterfaces" }
varlink_parser = { version = "2.1", path = "../varlink_parser" }
serde = "1"
serde_json = "1"
clap = "2"
failure_derive = "0.1.2"
failure = "0.1.2"

[dev-dependencies]
escargot = "0.3"
