[package]
name = "varlink-server-more"
version = "0.1.0"
authors = ["Harald Hoyer <harald@redhat.com>"]
build = "build.rs"

[dependencies]
varlink = { path = "../../varlink" }
serde = "1"
serde_derive = "1"
serde_json = "1"

[build-dependencies]
varlink = { path = "../../varlink" }
