[package]
name = "example"
version = "3.0.0"
authors = ["Harald Hoyer <harald@redhat.com>"]
edition = "2018"
publish = false

[dependencies]
varlink = { version = "7", path = "../../varlink" }
serde = "1"
serde_derive = "1"
serde_json = "1"
getopts = "0"
varlink_derive = { version = "0", path = "../../varlink_derive" }

chainerror = "0.4.2"
