[package]
name = "example"
version = "2.0.0"
authors = ["Harald Hoyer <harald@redhat.com>"]
build = "build.rs"
edition = "2018"
publish = false

[dependencies]
varlink = { version = "7", path = "../../varlink" }
serde = "1"
serde_derive = "1"
serde_json = "1"
getopts = "0"
chainerror = "0.4"

[build-dependencies]
varlink_generator = { version = "7", path = "../../varlink_generator" }
